---
- name: creation of user
  hosts: all
  tasks:  
   - name:
     user:
       name: "{{a}}"
       password: "{{b}}"  
       uid: "{{c}}"  
       comment: "{{d}}"  
       home: "{{e}}"  


   - name: creation of file
     file: 
       name: "{{f}}"
       state: "{{g}}"
...      
